language: python
python:
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
install:
  - pip install flake8
  - pip install coveralls
script:
  - flake8 .
  - coverage run --branch --source pyuca test.py
  - coverage run --branch --source pyuca full_test.py
after_success:
  - coveralls
