language: python
python:
  - "2.7"
  - "3.3"
install:
  - pip install flake8
  - pip install coveralls
script:
  - flake8 pyuca
  - coverage run --branch --source pyuca test.py
after_success:
  - coveralls
